[package]
name = "cxx-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = { workspace = true }
my-crate = { path = "../my-crate" }

[build-dependencies]
cxx-build = { workspace = true }
